### ISSUE TITLE
Will there be an r-build for Ubuntu 22.10 in the near future?

### ISSUE THREAD

**Issue by camilogarciabotero** [rstudio/r-builds#164]
Hi all,

Hey there! Thank you so much for your work on the r-builds repo! I was just wondering if there are any plans for an r-build for Ubuntu 22.10 anytime soon?

Thanks.

**Comment by glin** [comment]
Hi @camilogarciabotero, these R builds follow the [Posit platform support](https://posit.co/about/platform-support/), and we don't typically support non-LTS Ubuntu releases. So no Ubuntu 22.10 builds in the near future, but it may be possible to install the Ubuntu 22.04 binary there if there's no compatibility issue (I'm not actually sure). Or alternatively, you can get the distro default `r-base` package, or compile R from source as a last resort.

**Comment by camilogarciabotero** [comment]
Thank you for the quick answer, yeah I went directly to `r-base`. I was hoping to use `rig` to manage my `r` versions, but it is based on the `r-build` support. Guess I will stick to `r-base`.

**Comment by gaborcsardi** [comment]
I tried to install a 22.04 build on 22.10, and while it installs fine, it does not work, because Ubuntu updates library versions. 

E.g. on 22.04:
```
root@12002a66eb3f:~# apt-cache search libicu
libicu-dev - Development files for International Components for Unicode
libicu70 - International Components for Unicode
libicu-le-hb-dev - ICU Layout Engine API on top of HarfBuzz shaping library (development)
libicu-le-hb0 - ICU Layout Engine API on top of HarfBuzz shaping library
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization
```
and on 22.10:
```
root@57d8616d7a06:~# apt-cache search libicu
libicu-dev - Development files for International Components for Unicode
libicu71 - International Components for Unicode
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization
```
so the ICU library is newer and our build will fail.

I think our Ubuntu RStudio IDE builds actually do work on 22.10 as well, but those builds embed all the required libraries. If we wanted to support non-LTS releases in rstudio/rbuilds, that is considerably more work, as we need to update every 9 month, and one or two additional platforms, depending on which ones are supported by Ubuntu.

Nevertheless I'll make a note in the rig README that only LTS releases are supported currently.
