### ISSUE TITLE
unable to build for rhel-9. issues with Rprofile HTTPUserAgent string

### ISSUE THREAD

**Issue by wccropper** [rstudio/r-builds#231]
Fresh clone of the git repo
```
# export PLATFORM=rhel-9
# export R_VERSION=4.4.0
# export R_INSTALL_PATH=/data/apps/R/4.4.0
# make build-r-$PLATFORM
./build.sh: line 193: syntax error near unexpected token `%s'
make: *** [Makefile:58: build-r-rhel-9] Error 2
```

**Comment by wccropper** [comment]
Bump

**Comment by glin** [comment]
Hi, I can't reproduce this so this is strange... I'm not sure why that error would occur in the build script.

Could you try running a build manually like this, to see if it works or produces any more information? Instead of using Docker Compose, this will start a container session manually with Docker, then build R using the same options.
```sh
make docker-build-rhel-9
make bash-rhel-9

R_VERSION=4.4.0 R_INSTALL_PATH=/data/apps/R/4.4.0 ./build.sh
```

**Comment by wccropper** [comment]
This way worked for me. I built 4.4.0 and 4.4.1. So happy to close this. Not sure why the other way doesn;t work but as long as I have a path forward I am good!
